# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Pull Request Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
#     - uses: TimonVS/pr-labeler-action@v3
#       with:
#         configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     - name: PR Labeler
#       uses: paulfantom/periodic-labeler@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         GITHUB_REPOSITORY: ${{ github.repository }}
#         LABEL_MAPPINGS_FILE: .github/pr-labeler.yml

      - name: PR Labeler
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#           configuration-path: ".github/labeler.yml"
